


-- 1) Заходим в PostgreSQL UI и удаляем схему edo, если она есть
-- 2) Запускаем приложение:
-- Для запуска у вас должен быть запущен rabbitmq и postgreSQL.
-- Порядок запуска микросервисов: сервер, сервис, репозиторий, рест
-- Теперь появились таблицы, надо их заполнить тестовыми данными:
-- 1) В этом файле выбираем PostgreSQL диалект, если IDE предлагает это сделать
-- 2) Выбираем схему edo в бд edo_db(сверху справа, наводим на edo_db, нажимаем на клавиатуре вправо, выбираем edo, жмем ок)
-- 3) Выделяем весь текст, нажимаем кнопку play в верхней левой части экрана

-- Проверить работоспособность:
-- GET запрос на http://127.0.0.1:8080/api/rest/appeal/appealById/1
-- POST запрос на http://127.0.0.1:8080/api/rest/appeal    json можно найти в файле json_for_appeal_save_test или в таске#90




-- Заполнение таблицы employee тестовыми данными

insert into employee (first_name, last_name, middle_name, address, photo_url, fio_dative, fio_nominative, fio_genitive, external_id, phone, work_phone, birth_date, username, creation_date, archived_date, work_email) values
                      ('Иван', 'Иванов','Иванович','Невский 28','example.org','Иванову Ивану Ивановичу', 'Иванов Иван Иванович', 'Иванова Ивана Ивановича', '123', '89993332211','89992221133',now(),'ivan123', null, null, 'iv@ya.ru');
insert into employee (first_name, last_name, middle_name, address, photo_url, fio_dative, fio_nominative, fio_genitive, external_id, phone, work_phone, birth_date, username, creation_date, archived_date, work_email) values
    ('Игорь', 'Игорев','Игоревич','Невский 29','example1.org','Игореву Игорю Игоревичу', 'Игорев Игорь Игоревич', 'Игорева Игоря Игоревича', '124', '89993332212','89992221132',now(),'igor123', null, null, 'ig@ya.ru');
insert into employee (first_name, last_name, middle_name, address, photo_url, fio_dative, fio_nominative, fio_genitive, external_id, phone, work_phone, birth_date, username, creation_date, archived_date, work_email) values
    ('Иван', 'Петров','Иванович','Невский 28','example2.org','Петрову Ивану Ивановичу', 'Петров Иван Иванович', 'Петрова Ивана Ивановича', '124', '89993332213','89992221133',now(),'petrov123', null, null, 'petrov@ya.ru');


-- Заполнение таблицы author тестовыми данными
insert into author (first_name, last_name, middle_name, address, snils, mobile_phone, email, employment, fio_dative, fio_genitive, fio_nominative) values
    ('Иван', 'Иванов','Иванович','Невский 28','888999111','89991112233','iv@ya.ru','WORKER','Иванову Ивану Ивановичу','Иванова Ивана Ивановича', 'Иванов Иван Иванович');


-- Заполнение таблицы address тестовыми данными
insert into address (full_address, street, house, "index", housing, building, city, region, country, flat) values
    ('Ленинградская область, Поселок Кузнечное, улица Ленина, дом 7, кв 12', 'Ленина', '7', '333213','2','2','Кузнечное','Ленинградская область','РФ','12');


-- Заполнение таблицы question тестовыми данными
--
insert into question (creation_date, archived_date, summary, theme_id) values (now(), null, 'Осы залетают в окно', 6);


-- Заполнение таблицы resolution тестовыми данными

insert into resolution (creation_date, archived_date, last_action_date, resolution_name, creator_id, signer_id, curator_id, question_id) values
    (null, null, null, 'Запрос', '1','1','1','1');

-- Заполнение таблицы file_pool тестовыми данными

insert into file_pool (storage_file_id, file_name, extension, file_size , page_count, upload_date, archived_date, creator_id) values
    ('0fd52378-819e-47f3-bd58-293edd25ed0a', 'cat', 'jpg', '1', '1', null, null, 1);



-- Заполнение таблицы nomenclature тестовыми данными

insert into nomenclature (creation_date, archived_date, template, current_value, "index") values
    (now(),null, '%ЧИС%ГОД-%ЗНАЧ/2', 1, '617234');

-- Заполнение таблицы department тестовыми данными


insert into department (short_name, full_name, address_id, archived_date, creation_date, external_id, phone, department_id) values
    ('УВУ', 'Управление всеми управлениями', 1, null, now(), 1, '88889993322', 1);

-- Заполнение таблицы appeal тестовыми данными
insert into appeal (creation_date, archived_date, number, annotation, creator_id, nomenclature_id, appeal_status, way_to_receive, way_to_answer) VALUES
    (now(),null, '12', 'Обращение', 1, 1, 'NEW', 'ON_PAPER', 'BY_RUSSIAN_POST');


-- На всякий
CREATE TABLE if not exists approval_sheet
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approval_urgency      VARCHAR(255)                            NOT NULL,
    parent_approval_sheet BIGINT,
    initiator_comment     VARCHAR(255),
    creation_date         TIMESTAMP with time zone                NOT NULL,
    referral_date         TIMESTAMP with time zone,
    signing_date          TIMESTAMP with time zone,
    archived_date         TIMESTAMP with time zone,
    number                VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_approval_sheet PRIMARY KEY (id)
);

ALTER TABLE if exists  approval_sheet
    ADD CONSTRAINT FK_APPROVAL_SHEET_ON_PARENT_APPROVAL_SHEET  FOREIGN KEY  (parent_approval_sheet) REFERENCES approval_sheet (id);

comment on column approval_sheet.approval_urgency is 'Срочность рассмотрения';
comment on column approval_sheet.parent_approval_sheet is 'Ссылка на родительский лист согласования';
comment on column approval_sheet.initiator_comment is 'Комментарий инициатора';
comment on column approval_sheet.creation_date is 'Дата создания листа согласования';
comment on column approval_sheet.referral_date is 'Дата перевода направления на согласование';
comment on column approval_sheet.signing_date is 'Дата подписания';
comment on column approval_sheet.archived_date is 'Дата перевода в архив';
comment on column approval_sheet.number is 'Номер листа согласования';


-- Заполнение таблицы approval_sheet тестовыми данными
insert into approval_sheet (approval_urgency, parent_approval_sheet, initiator_comment, creation_date, referral_date, signing_date, archived_date, number) values
    ('Срочная', 1, '...', now(), null, null, null, '93939');




--Добавление строк в таблицу theme тема 15
INSERT INTO theme (theme_name, code)
VALUES
       ('социальные льготы для ветеранов', '3.4');

--Добавление внешнего ключа в таблицу theme
UPDATE theme
SET parent_id = (SELECT theme.id FROM theme where code = '3')
where code in ('3.4');
