security:
  enabled: false
minio:
    accessKey: ACCESS_KEY
    secretKey: ACCESS_SECRET
    endpoint: http://localhost:9000
    bucket: test
spring:
#  profiles:
#    include: security
  application:
    name: edo-file-storage
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
