spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    enabled: true

